#!/usr/bin/env node
// Inline the brevity spec (and optionally a project dictionary) into an AGENTS.md file, between
// marker comments, idempotently. For agents that read AGENTS.md but cannot import other files
// (Codex, and most AGENTS.md readers): the text has to be inlined.
//
//   node tools/agents-md.mjs <AGENTS.md> [--dict <DICT.md>]... [--remove]
//
// Re-running replaces the block in place; --remove deletes it. Everything outside the markers is kept.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const remove = args.includes('--remove');
const dicts = args.flatMap((a, i) => (args[i - 1] === '--dict' ? [a] : []));
const target = args.find((a, i) => !a.startsWith('--') && args[i - 1] !== '--dict');
if (!target) {
  console.error('usage: agents-md.mjs <AGENTS.md> [--dict <DICT.md>]... [--remove]');
  process.exit(2);
}

const BEGIN = '<!-- brevity:begin (generated by tools/agents-md.mjs; edits inside are overwritten) -->';
const END = '<!-- brevity:end -->';
const block = [BEGIN, readFileSync(join(root, 'SPEC.md'), 'utf8').trim(),
  ...dicts.map((d) => readFileSync(d, 'utf8').trim()), END].join('\n\n');

const before = existsSync(target) ? readFileSync(target, 'utf8') : '';
const start = before.indexOf('<!-- brevity:begin');
const stop = before.indexOf(END);
let after;
if (start >= 0 && stop > start) {
  const head = before.slice(0, start).replace(/\s*$/, '');
  const tail = before.slice(stop + END.length).replace(/^\s*/, '');
  after = [head, remove ? '' : block, tail].filter(Boolean).join('\n\n') + '\n';
} else if (remove) {
  after = before;
} else {
  after = (before.trim() ? `${before.replace(/\s*$/, '')}\n\n` : '') + `${block}\n`;
}
writeFileSync(target, after);
const bytes = Buffer.byteLength(after);
console.log(`${remove ? 'removed from' : 'wrote'} ${target} (${bytes} bytes${bytes > 32768 ? '; over Codex\'s default 32 KiB project_doc_max_bytes' : ''})`);
